language: objective-c
osx_image: xcode9.3
script:
  - xcodebuild test -project Interstellar.xcodeproj -scheme Interstellar_iOS -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 6 Plus,OS=11.3' | xcpretty -c;
  - xcodebuild build -project Interstellar.xcodeproj -scheme Interstellar_iOS -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -configuration Release | xcpretty -c;
  - xcodebuild build -project Interstellar.xcodeproj -scheme Interstellar_OSX -sdk macosx ONLY_ACTIVE_ARCH=NO -configuration Release | xcpretty -c;
  - xcodebuild build -project Interstellar.xcodeproj -scheme Interstellar_tvOS -sdk appletvsimulator ONLY_ACTIVE_ARCH=NO -configuration Release | xcpretty -c;
  - xcodebuild build -project Interstellar.xcodeproj -scheme Interstellar_watchOS -sdk watchsimulator ONLY_ACTIVE_ARCH=NO -configuration Release | xcpretty -c;
  - swift test
