language: objective-c
osx_image: xcode8

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - PROJECT="Interstellar.xcodeproj"
    - IOS_FRAMEWORK_SCHEME="Interstellar_iOS"
    - MACOS_FRAMEWORK_SCHEME="Interstellar_macOS"
    - TVOS_FRAMEWORK_SCHEME="Interstellar_tvOS"
    - WATCHOS_FRAMEWORK_SCHEME="Interstellar_watchOS"
    - IOS_SDK=iphonesimulator10.0
    - MACOS_SDK=macosx10.12
    - TVOS_SDK=appletvsimulator10.0
    - WATCHOS_SDK=watchsimulator3.0
  matrix:
    - DESTINATION="OS=10.0,name=iPhone 5"           SIMULATOR="iPhone 5"                             SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"
    - DESTINATION="OS=10.0,name=iPhone 5S"          SIMULATOR="iPhone 5s"                            SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"
    - DESTINATION="OS=10.0,name=iPhone SE"          SIMULATOR="iPhone SE"                            SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"
    - DESTINATION="OS=10.0,name=iPhone 6"           SIMULATOR="iPhone 6"                             SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"
    - DESTINATION="OS=10.0,name=iPhone 6 Plus"      SIMULATOR="iPhone 6 Plus"                        SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"
    - DESTINATION="OS=10.0,name=iPhone 6S"          SIMULATOR="iPhone 6s"                            SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"
    - DESTINATION="OS=10.0,name=iPhone 6S Plus"     SIMULATOR="iPhone 6s Plus"                       SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"
    - DESTINATION="arch=x86_64"                     SIMULATOR=""                                     SCHEME="$MACOS_FRAMEWORK_SCHEME"   SDK="$MACOS_SDK"   RUN_TESTS="YES"
    - DESTINATION="OS=10.0,name=Apple TV 1080p"     SIMULATOR="Apple TV 1080p"                       SCHEME="$TVOS_FRAMEWORK_SCHEME"    SDK="$TVOS_SDK"    RUN_TESTS="YES"
    - DESTINATION="OS=3.0,name=Apple Watch - 38mm"  SIMULATOR="Apple Watch - 38mm"                   SCHEME="$WATCHOS_FRAMEWORK_SCHEME" SDK="$WATCHOS_SDK" RUN_TESTS="NO"

before_script:
  - export IOS_SIMULATOR_UDID=`xcrun simctl list devices | grep "$SIMULATOR (" | awk -F '[ ]' '{ print $7 $8 $9 }' | awk -F '[\(]' '{print $2}' | sed 's/.$//'`
  - echo $IOS_SIMULATOR_UDID
  - open -a "simulator" --args -CurrentDeviceUDID $IOS_SIMULATOR_UDID

script:
  - set -o pipefail
  - swiftlint
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c;
    else
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi

  # Build Framework in Release and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO test | xcpretty -c;
    else
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi

notifications:
  email: false
